### ISSUE TITLE
Appear Offline not working on login need to manually apply it again via taskbar

### ISSUE THREAD

**Issue by githobnob** [molenzwiebel/Deceive#10]
After latest patch deceive is not showing offline on login and needs to be toggled via taskbar icon > Status > Offline to work. Tested this with two clients which shows that you are Online once logged in and then offline once it is triggered through the status menu. Tested on EUW.

**Comment by molenzwiebel** [comment]
This should be fixed on v1.5.0. Please let me know if it isn't.
