### ISSUE TITLE
Wondering if logging into another chat account can be done

### ISSUE THREAD

**Issue by dragitz** [molenzwiebel/Deceive#100]
I remember years ago while I was editing the old flash client, there was a file named ClientLibChat.dat
in it you could hardcode your credentials and log into that account chat.

Now I'm exploring your code and see that a JWT can be replaced with another valid one and wondering if we could log into another account.

Do you think it can be done via Jwt replacement?

**Comment by aPinat** [comment]
I don't quite understand what you would want to do or what the point of this is.
Of course if you swap the auth JWT you will be logged onto the other account, but can't you just login to a different account in the Riot Client directly? 
Deceive is essentially just MITM proxying between Riots servers and RC anyways, so there is no real use.

**Comment by dragitz** [comment]
I just want to try a few tricks with the client so I can play with my main and chat with my alt in the client.
Thank you for helping!
