### ISSUE TITLE
Deceive + LoR crashes are startup with System Error

### ISSUE THREAD

**Issue by Pikachews** [molenzwiebel/Deceive#107]
LoR manages to start up and hit the loading screen when used with deceive, but ends up displaying the following error after it finishes loading (before the lobby screen is displayed):

![image](https://user-images.githubusercontent.com/5668416/126212487-a3c45e19-924a-4800-ba69-b644f4c172dc.png)

Without Deceive, the game starts up fine.

**Comment by molenzwiebel** [comment]
Apologies for the late response. I cannot reproduce this locally. Are you still experiencing this issue? If you are, please let me know the exact steps you're taking and then reopen the issue.
