### ISSUE TITLE
Detected as malware

### ISSUE THREAD

**Issue by Sharingisnotillegal** [molenzwiebel/Deceive#11]
First of all. I highly doubt this is malware.

Now when we got that out of the way. I don't have the brains to understand why this is triggered by some "ai" anti-viruses as a virus.
I just wish it didn't, as it still makes you think^^

VirusTotal antivirus site detects as malware
SecureAge APEX | Malicious
Bkav | W32.HfsAutoB.
Endgame | Malicious (high Confidence)

https://www.virustotal.com/gui/file/463ed1c1c4b91134c2224996c6a8015f146990e6b7f7e0837f241f953ab05a90/detection
Version v1.3.1 

MD54ec83880d96fede80b898f33de0fd11c
SHA-1f936c8d1203bdbd845e27d281af23281ebf11fd0
SHA-256463ed1c1c4b91134c2224996c6a8015f146990e6b7f7e0837f241f953ab05a90 

Thank you for your time

**Comment by ITALIA195** [comment]
If you see only a handful of positives you can assume that those are false positives.

I've scanned the executable with pestudio, you can do the same and get a general idea of why it gets flagged as malicious by some antivirus.
Every antivirus detects viruses by first checking if it's in their virus database (by hashing the program) and after that they search for patterns within the application that resembles those you would find in a virus. 

Here are some things I've found that may trick the antivirus into thinking this is a virus:

1. Creates a socket (which it uses to intercept league packets) meaning it has a low level network activity, malware might want to do that to comunicate with a remote server
1. It uses reflection (It's actually used by a library that the project references). Malware often use reflection to hide malicious code. (Example: In an embedded resource attached to the executable) 
1. It scans for processes. Almost every antivirus will flag process scanning, viruses use it to search for processes to inject code to or to check if the virus is being run in an analysis environment/VM.

**Comment by molenzwiebel** [comment]
Yep. The likely trigger is Fody.Costura, which is used for bundling all the libraries and dependencies into a single .exe. It does that by dynamically unpacking and loading the bundled code at runtime, which is similar to how malware extracts and runs its encrypted payloads. That being said, like @ITALIA195 says, almost every VirusTotal scan has a few false positives. As always, you can inspect the code and compile it for yourself if you're (overly) cautious.
