### ISSUE TITLE
How do I uninstall this program

### ISSUE THREAD

**Issue by PuraAnimaMea** [molenzwiebel/Deceive#117]
I am not able to find the program in my control panel in order to uninstall it.

**Comment by lorenzua02** [comment]
Just delete the .exe file, deceive isn't "installed" on your computer

**Comment by molenzwiebel** [comment]
Yep, Deceive doesn't leave anything other than the executable. If you don't launch League using Deceive, nothing happens. Simply deleting the exe is enough to uninstall.
