### ISSUE TITLE
Changing game language using Deceive

### ISSUE THREAD

**Issue by Alexandre-Itabayana** [molenzwiebel/Deceive#119]
I'm having a issue where i want to change the language from the game, and since it doesnt let me (BR server, want to put an en_US locale) i have to do it through the shortcut, since it replaces the config files when i launch the client, want to know if there is a way to do that through deceive.

**Comment by Kiruscha** [comment]
How did you solve this? I am having the same exact issue.

**Comment by Kiruscha** [comment]
Alright. Somehow I solved it. Dunno which workaround did it in the end.

**Comment by Alexandre-Itabayana** [comment]
same here, but i had a problem where my window wouldnt load, so i had to
return it to original

Em qui., 9 de dez. de 2021 às 20:54, Kiruscha ***@***.***>
escreveu:
