### ISSUE TITLE
unable to write configuration file

### ISSUE THREAD

**Issue by Raenef** [molenzwiebel/Deceive#125]
![220213_error](https://user-images.githubusercontent.com/89660477/153770767-4ce52545-1cc7-4edd-b7d5-1fde22b041ed.PNG)

Hi it worked nicely for quite a while but at the end of this week this started to appear

**Comment by Hikra** [comment]
Got the same error, waiting for a response too.

**Comment by Spud18** [comment]
+1, Same error.

**Comment by RafalMakac** [comment]
Same error.

**Comment by zeinterrupter** [comment]
same error for me!

**Comment by zeinterrupter** [comment]
Appreciate the response, it only did this twice in one session and yeah you could click it away but it was bothersome because it pulled the screen into frame and tabbed my game mid play.

Will try the new one, thank you for the continued support on this!

**Comment by molenzwiebel** [comment]
This should be solved with Deceive v1.11.0. Let me know if you continue to run into issues with the new version.
