### ISSUE TITLE
Running Deceive causes League client to display Account Suspended message as of 3/12/2022

### ISSUE THREAD

**Issue by HutchMD** [molenzwiebel/Deceive#126]
Running the League client normally will remove the message and you can actually play the game.
Running Deceive will cause the client to not load, and instead give you a permaban notification.

![Permaban](https://user-images.githubusercontent.com/17505904/158012477-7ab57330-43b3-45ac-9246-98a327fbc140.PNG)

**Comment by OdaSamurai** [comment]
I'm pretty sure deceive has nothing to do with this, as many players have had this massage in the last few days

Maybe it was just a coincidence that it worked as you turned Deceive off, turn it back on and take a look
