### ISSUE TITLE
What is the IP Address of the NA chat servers

### ISSUE THREAD

**Issue by Brandon-Huu** [molenzwiebel/Deceive#128]
I would like to block the leagues chat in my firewall

**Comment by molenzwiebel** [comment]
Literally the first result for "appear offline league of legends" contains IP addresses for both NA and EU: https://leaguefeed.net/how-to-appear-offline-in-league-of-legends/

If those are wrong, you can always resolve the current IP for `na2.chat.si.riotgames.com`, which is the host for NA (assuming you're not on a migrated account).

**Comment by Brandon-Huu** [comment]
Thanks for "na2.chat.si.riotgames.com" but that didn't seem to work either. Do you know any better places to ask?

No one seems to know anything about this
