### ISSUE TITLE
Unable to run valorant 

### ISSUE THREAD

**Issue by Squedgame** [molenzwiebel/Deceive#133]
Whenever I open the application as usual an error occurs, only happened post update

![image](https://user-images.githubusercontent.com/104873182/166590577-3f6260c2-f6b0-4977-ae22-0caa42cd0304.png)

**Comment by Jerem584** [comment]
run deceive as admin

**Comment by Squedgame** [comment]
> run deceive as admin

Okay, Ty!

It worked perfectly fine after this!

**Comment by Jerem584** [comment]
most of user related error can be fixed if you look closely at the error 

https://cdn.discordapp.com/attachments/249481856687407104/971192305451167774/unknown.png
