### ISSUE TITLE
Error when checked the box to skip game choice option and chose League of Legends

### ISSUE THREAD

**Issue by sand5456** [molenzwiebel/Deceive#134]
![image](https://user-images.githubusercontent.com/14275938/166609407-96b136e0-8003-4cc0-b37b-0de80965cd53.png)

**Comment by s3714110** [comment]
I had the exact same issue. I tried redownloading it but still got this error. 1.10 still works fine tho

**Comment by molenzwiebel** [comment]
Run as administrator.
