### ISSUE TITLE
Clicking "Deceive.exe" does not run even with Administrator permissions.

### ISSUE THREAD

**Issue by rahkee** [molenzwiebel/Deceive#135]
OS Name	Microsoft Windows 10 Pro
Version	10.0.19043 Build 19043
Other OS Description 	Not Available
OS Manufacturer	Microsoft Corporation
Processor	Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz, 3401 Mhz, 4 Core(s), 8 Logical Processor(s)
Hardware Abstraction Layer	Version = "10.0.19041.1566"

**Comment by Hikra** [comment]
Same problem

**Comment by Hikra** [comment]
I've fixed the issue by installing this:

https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-6.0.4-windows-x64-installer

Got helped from a message on their discord.

**Comment by molenzwiebel** [comment]
Interesting. The application is supposed to prompt you to install the .NET 6 runtime. Did you perhaps miss this alert?

![image](https://user-images.githubusercontent.com/3594254/166676485-c42bbc9e-7bf8-48a5-8eb3-747a7a4176d9.png)

I'd be concerned if Deceive simply does not run without any message (to the point of downgrading back to 4.8). @aPinat?

**Comment by aPinat** [comment]
Yeah that wouldn't be good at all.
It should definitely prompt. Perhaps it is being blocked by Defender or other Antivirus from launching at all?
However I would rather do a self-contained build, than going to 4.8 since .NET Framework doesn't really have a future...

**Comment by molenzwiebel** [comment]
We've moved back to .NET Framework until Microsoft sorts out their issues. Please try the new build [here](https://github.com/molenzwiebel/Deceive/releases/tag/v1.11.0) and let us know if you run into trouble.
