### ISSUE TITLE
Windows Defender false positive on Deceive v1.11.0

### ISSUE THREAD

**Issue by EinAeffchen** [molenzwiebel/Deceive#136]
As the title suggests the compiled exe seems to contain the Wacatac.B!ml trojan virus

**Comment by in1x** [comment]
mine game me this
![image](https://user-images.githubusercontent.com/90496583/166675132-33044bad-89a5-4c3a-a223-61fc5286c1c6.png)

**Comment by molenzwiebel** [comment]
Windows Defender seems to incorrectly flag the new release. I've submitted a sample to Microsoft to get it cleared.

You can add an exception for the binary in your antivirus software, or compile the software from source.

I'll leave this open until the binary is no longer incorrectly flagged.

**Comment by molenzwiebel** [comment]
I've uploaded a new build on the release page ([here](https://github.com/molenzwiebel/Deceive/releases/tag/v1.11.0)) which does not get flagged by Windows Defender. Please let me know if you use a different antivirus program that does flag it.
