### ISSUE TITLE
Error and could not proprely initializate itself

### ISSUE THREAD

**Issue by ViperTeuz** [molenzwiebel/Deceive#139]
i cant run the file .exe and give me this error with a several line of error

**Comment by ViperTeuz** [comment]
![bbfc000e-6d29-46a6-9829-b3c47af0c3e0](https://user-images.githubusercontent.com/105673476/168668190-eacabf88-e41d-4623-a654-f7aa61f13ed6.jpg)

**Comment by molenzwiebel** [comment]
Launch game once normally, then launch Deceive again.
