### ISSUE TITLE
Device cant open

### ISSUE THREAD

**Issue by MisterDiego1** [molenzwiebel/Deceive#140]
![image](https://user-images.githubusercontent.com/105695593/168734744-6ec07d5c-182a-46ac-8f8f-82a44c77b705.png)
Sup, molenzwiebel! Deceive for lol chat is showing an error whenever I open it. I can't see my chat even with the program closed. Here is a screenshot of the error, can you help me?
I've already tried a few things, like starting as admin, uninstalled lol and Deceive and the error still persists :c
Thanks!

**Comment by molenzwiebel** [comment]
Did you previously try appear offline by blocking League's chat servers in your firewall? You'll need to remove those rules, because they also prevent Deceive from connecting.

**Comment by MisterDiego1** [comment]
No, i will try and I tell you.

**Comment by MisterDiego1** [comment]
so, i managed to fix it by disabling the firewall. Obrigado pela ajuda

**Comment by fgtyi57tdio** [comment]
ich hab das gleiche Problem was muss ich machen?

**Comment by MisterDiego1** [comment]
You should disable your firewall and open Deceive normally.
As a long-term measure you should make an exception in your firewall for it to work normally.
Sorry for the translation.
Sie sollten Ihre Firewall deaktivieren und Deceive normal öffnen.
Als langfristige Maßnahme sollten Sie in Ihrer Firewall eine Ausnahme machen, damit sie normal funktioniert.
Sorry für die Übersetzung.
