### ISSUE TITLE
Couldnt properly initialize

### ISSUE THREAD

**Issue by webst88** [molenzwiebel/Deceive#141]
![Capture](https://user-images.githubusercontent.com/106407539/170784841-fcd67181-32dd-4fb2-afa0-23c48e8c090f.PNG)

Whats that Error? It was working the day before. Nothing changed.

**Comment by Rangertreaty33** [comment]
Yeah just got this error today, 5-27-2022. Was last working for me as of 5-26-2022.

**Comment by molenzwiebel** [comment]
Launch game normally once, then relaunch Deceive.
