### ISSUE TITLE
Friends list not loading

### ISSUE THREAD

**Issue by cameronscottgibson** [molenzwiebel/Deceive#144]
As of the latest patch, my friends list does not load and in-client chat (such as post game chat) does not work when I launch league with Deceive. I have attached an image of my friends list but it just loads

![image](https://user-images.githubusercontent.com/51902719/175107059-b5c7b4a9-2b49-4bd3-8a6a-a2ebf718d015.png)

**Comment by molenzwiebel** [comment]
Please try the following things:

- Disable your firewall entirely and restart both League and Deceive. If this fixes it, try adding an exception for Deceive and/or League in your firewall.
- If you previously blocked chat using firewall-based methods (such as netsh advfirewall), make sure to remove those blocks before running deceive.
- If you are using antivirus software, make sure it is not blocking Deceive.
- Try running Deceive as administrator (right-click Deceive.exe, "Run as administrator")

If none of these work, please upload your Deceive logs. They can be found in `%AppData%/Deceive/debug.log`.

**Comment by cameronscottgibson** [comment]
Followed all steps without success. (Firewall already disabled, don't use antivirus, and ran as admin). Attached my debug log

[debug.log](https://github.com/molenzwiebel/Deceive/files/8972316/debug.log)

**Comment by cameronscottgibson** [comment]
@molenzwiebel Any ideas?

**Comment by Kleeniie** [comment]
@cameronscottgibson, in my case I've fixed this issue by excluding Deceive from Kaspersky's port scanning. Try doing something similar with your antivirus/firewall!

**Comment by molenzwiebel** [comment]
Closing this for lack of further information. Please try [Deceive v1.12.0](https://github.com/molenzwiebel/Deceive/releases/tag/v1.12.0) and let me know if you still encounter issues.
