### ISSUE TITLE
Latest Valorant Update Third party policies 

### ISSUE THREAD

**Issue by magizhchi99** [molenzwiebel/Deceive#145]
Hi, 

Recently, Riot tweeted out this https://twitter.com/PlayVALORANT/status/1539728676815642624?t=jaIPeYYSe-SrbbU7ud4NGQ&s=19

Does this affect Deceive in any way? Thanks!

**Comment by molenzwiebel** [comment]
It's all fine. Deceive is registered on Riot's developer portal and complies with the points lined out in the article.
