### ISSUE TITLE
Insufficient Permissions

### ISSUE THREAD

**Issue by SVL17** [molenzwiebel/Deceive#149]
When I download the latest version, the application does not open saying "Insufficient Permissions" (I am the only user on my PC).  Sometimes the application will download but when I go to log in the game closes and the application is nowhere to be seen on my PC.

**Comment by molenzwiebel** [comment]
You have an antivirus installed that is attempting to quarantine or remove Deceive. You'll need to add an exception for it. Exactly how will depend on which specific antivirus you use, but google should be able to help you out there.
