### ISSUE TITLE
Version Mismatch - VALORANT

### ISSUE THREAD

**Issue by DanBlock-dev** [molenzwiebel/Deceive#150]
Decieve on my Friends List says 'Version Mismatch' unsure why and how to fix that.
![Valo_Decieve](https://user-images.githubusercontent.com/82678779/179823862-ca8918cc-8e1e-4b30-8148-36833170c129.png)

**Comment by molenzwiebel** [comment]
Please search older issues before leaving a comment:

https://github.com/molenzwiebel/Deceive/issues/112 https://github.com/molenzwiebel/Deceive/issues/78 https://github.com/molenzwiebel/Deceive/issues/73 https://github.com/molenzwiebel/Deceive/issues/95 https://github.com/molenzwiebel/Deceive/issues/101 https://github.com/molenzwiebel/Deceive/issues/132
