### ISSUE TITLE
Friendlist randomly disconnecting

### ISSUE THREAD

**Issue by imflez** [molenzwiebel/Deceive#154]
this doesn't happen when opening league normally, just with deceive 
![image](https://user-images.githubusercontent.com/89546983/184432633-e44e65e7-55b5-43a6-a3c5-8a618adf0574.png)
it's not my internet connection

**Comment by Indeedornot** [comment]
Do you happen to have some antivirus software installed?  It might be blocking the requests for friendship list

**Comment by molenzwiebel** [comment]
Please try the following things:

- Disable your firewall entirely and restart both League and Deceive. If this fixes it, try adding an exception for Deceive and/or League in your firewall.
- If you previously blocked chat using firewall-based methods (such as netsh advfirewall), make sure to remove those blocks before running deceive.
- If you are using antivirus software, make sure it is not blocking Deceive.
- Try running Deceive as administrator (right-click Deceive.exe, "Run as administrator")

If none of these work, please upload your Deceive logs. They can be found in `%AppData%/Deceive/debug.log`.

**Comment by imflez** [comment]
> Do you happen to have some antivirus software installed? It might be blocking the requests for friendship list

it is not, i checked

**Comment by imflez** [comment]
> Please try the following things:
> 
> * Disable your firewall entirely and restart both League and Deceive. If this fixes it, try adding an exception for Deceive and/or League in your firewall.
> * If you previously blocked chat using firewall-based methods (such as netsh advfirewall), make sure to remove those blocks before running deceive.
> * If you are using antivirus software, make sure it is not blocking Deceive.
> * Try running Deceive as administrator (right-click Deceive.exe, "Run as administrator")
> 
> If none of these work, please upload your Deceive logs. They can be found in `%AppData%/Deceive/debug.log`.
[debug.log](https://github.com/molenzwiebel/Deceive/files/9331532/debug.log)

**Comment by molenzwiebel** [comment]
This should be fixed with [Deceive v1.12.0](https://github.com/molenzwiebel/Deceive/releases/tag/v1.12.0). Please let me know if you still encounter this issue.
