### ISSUE TITLE
The latest version stopped working, had to use the older one.

### ISSUE THREAD

**Issue by July96** [molenzwiebel/Deceive#157]

**Comment by whitedev93** [comment]
same here, v1.8 is working to me

**Comment by anfractu0us** [comment]
same, about to try using an older version, attempted to both use different accounts and also log into said accounts with the client sans deceive but doesn't seem to matter, all result in the landing screen never loading as such:
![image](https://user-images.githubusercontent.com/9019885/188851967-9bcb88c8-f1fe-4d58-912a-efa97efb97a0.png)

**Comment by ezFrost1** [comment]
Having problems as well with Valorant. Seems to be a connection issue, keep getting error code 43.

**Comment by Pipoun30** [comment]
Hey guys, for my part I found a solution on my side to solve the problem, launch deceive 1.8 version, connect then disconnect and then launch Deceive 1.11.0 (Lastest version) And Enjoy

**Comment by molenzwiebel** [comment]
This should be fixed with [Deceive v1.12.0](https://github.com/molenzwiebel/Deceive/releases/tag/v1.12.0). Please let me know if you still encounter this issue.
