### ISSUE TITLE
Deceive V1.12 

### ISSUE THREAD

**Issue by ezFrost1** [molenzwiebel/Deceive#158]
Booted up V1.12, I am still getting Valorant error 43 and infinite loading in League Of Legends.

**Comment by Synaelle** [comment]
![image](https://user-images.githubusercontent.com/29670037/189040256-09e6020d-cc2a-4568-b0fe-33dcd80ff35d.png)
Yep I still have the issue

**Comment by molenzwiebel** [comment]
Please try the following things:

- Disable your firewall entirely and restart both League and Deceive. If this fixes it, try adding an exception for Deceive and/or League in your firewall.
- If you previously blocked chat using firewall-based methods (such as netsh advfirewall), make sure to remove those blocks before running deceive.
- If you are using antivirus software, make sure it is not blocking Deceive.
- Try running Deceive as administrator (right-click Deceive.exe, "Run as administrator")

If none of these work, please upload your Deceive logs. They can be found in `%AppData%/Deceive/debug.log`.

**Comment by ezFrost1** [comment]
Ran it as administrator and it fixed the problem. Thanks!
