### ISSUE TITLE
Friend's list not available

### ISSUE THREAD

**Issue by lunaq00** [molenzwiebel/Deceive#159]
I have this problem a couple weeks ago where my friend's list is not available.Same as the chat so i can't talk or invite anyone. I tried every solution you reply to the people having my same problem but nothing happend. I also installed the new version but nothing

**Comment by molenzwiebel** [comment]
Please upload your Deceive logs. They can be found in `%AppData%/Deceive/debug.log`.

**Comment by lunaq00** [comment]
[debug..txt](https://github.com/molenzwiebel/Deceive/files/9539036/debug.txt)

**Comment by michaelkr1** [comment]
This has started occurring for me too. Logs attached

[debug.log](https://github.com/molenzwiebel/Deceive/files/9663857/debug.log)

**Comment by Garu99** [comment]
I also have the same situation
[debug.log](https://github.com/molenzwiebel/Deceive/files/10298839/debug.log)

**Comment by molenzwiebel** [comment]
Please check if you still experience this on [v1.13.0](https://github.com/molenzwiebel/Deceive/releases/tag/v1.13.0), and leave a comment if you do.
