### ISSUE TITLE
Login error in Valorant

### ISSUE THREAD

**Issue by Astrow25** [molenzwiebel/Deceive#160]
![image](https://user-images.githubusercontent.com/76118368/189383543-40c180cd-6988-4070-9513-ea25b3d7fc10.png)
(I tested without Deceive and the game works perfectly (only happens on the latest version)

**Comment by ezFrost1** [comment]
Had this issue, running it in administrator solved the problem for me.

**Comment by Astrow25** [comment]
Personally, it doesn't work for me :/
