### ISSUE TITLE
Cannot launch game

### ISSUE THREAD

**Issue by Krumszz** [molenzwiebel/Deceive#161]
I'm suddenly not able to launch my game with deceive. I have tried deleting and downloading deceive again but its the same problem. It either gives me the error telling me to restart my game(VAL 62) or it just stays on the "riot games" screen forever.

**Comment by yoimlive777** [comment]
Same. League and Val don't work. Val gives an error and League just loads infinitely.

**Comment by molenzwiebel** [comment]
This should be resolved. Please feel free to reach out if you're still having issues on the latest release.
