### ISSUE TITLE
help

### ISSUE THREAD

**Issue by putotoy** [molenzwiebel/Deceive#163]
im trying to translate the source (c#) to python
but my goal is to add/change anything i can add/change to VALORANT even i can only see that.
is it possible? like (player cards valo)?
thankssss.
![post](https://user-images.githubusercontent.com/24718444/198881670-1603582d-fc58-4d14-b18f-fa5f9c8337c7.png)

**Comment by Krumszz** [comment]
I don't think you should mess with this game like that. You could get banned.

**Comment by molenzwiebel** [comment]
I will not be offering any non-Deceive related help on modifying client data. As @Krumszz mentioned, what you are doing is very likely to break the ToS and you should prepare yourself for potential bans.
