### ISSUE TITLE
Decieve is being flagged as a trojan, wanted to know if this is a false positive or not.

### ISSUE THREAD

**Issue by Jimothyy** [molenzwiebel/Deceive#168]
![image](https://user-images.githubusercontent.com/118230651/201796159-c0038658-0c0d-4a6d-90ee-df49a2fdd1de.png)

https://www.virustotal.com/gui/file/bf33ffff83a2a70050bd4c7ad562b908ba10da922bde4643b9c1034b7e45234b/detection

**Comment by molenzwiebel** [comment]
False positive.

**Comment by Jimothyy** [comment]
thanks man
