### ISSUE TITLE
Not Working (league)

### ISSUE THREAD

**Issue by Erenaaaa** [molenzwiebel/Deceive#171]
Since the latest version it takes forever to launch league of legends, the friend list is infinitely loading, and trying to disable decieve in the system tray causes some error to pop up, here's the exact error message bc i'm not big brain enough to know what it means;

************** Exception Text **************
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'SslStream'.
   at System.Net.Security.SslState.CheckThrow(Boolean authSuccessCheck, Boolean shutdownCheck)
   at System.Net.Security.SslState.get_SecureStream()
   at System.Net.Security.SslStream.BeginWrite(Byte[] buffer, Int32 offset, Int32 count, AsyncCallback asyncCallback, Object asyncState)
   at System.IO.Stream.<>c.<BeginEndWriteAsync>b__53_0(Stream stream, ReadWriteParameters args, AsyncCallback callback, Object state)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncTrim[TInstance,TArgs](TInstance thisRef, TArgs args, Func`5 beginMethod, Func`3 endMethod)
   at System.IO.Stream.BeginEndWriteAsync(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Stream.WriteAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   at System.IO.Stream.WriteAsync(Byte[] buffer, Int32 offset, Int32 count)
   at Deceive.MainController.<SendMessageFromFakePlayerAsync>d__77.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Deceive.MainController.<<UpdateTray>b__70_2>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4515.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
Deceive
    Assembly Version: 1.11.0.0
    Win32 Version: 1.11.0.0
    CodeBase: file:///C:/Users/erena/Desktop/Deceive.exe
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4536.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.CommandLine.DragonFruit
    Assembly Version: 0.4.0.0
    Win32 Version: 1.11.0.0
    CodeBase: file:///C:/Users/erena/Desktop/Deceive.exe
----------------------------------------
netstandard
    Assembly Version: 2.0.0.0
    Win32 Version: 4.8.4161.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/netstandard/v4.0_2.0.0.0__cc7b13ffcd2ddd51/netstandard.dll
----------------------------------------
System.CommandLine
    Assembly Version: 2.0.0.0
    Win32 Version: 1.11.0.0
    CodeBase: file:///C:/Users/erena/Desktop/Deceive.exe
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4579.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Net.Http
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4161.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Net.Http/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Net.Http.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4550.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4395.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.CommandLine.Rendering
    Assembly Version: 0.4.0.0
    Win32 Version: 1.11.0.0
    CodeBase: file:///C:/Users/erena/Desktop/Deceive.exe
----------------------------------------
System.ValueTuple
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4161.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ValueTuple/v4.0_4.0.0.0__cc7b13ffcd2ddd51/System.ValueTuple.dll
----------------------------------------
System.CommandLine.NamingConventionBinder
    Assembly Version: 2.0.0.0
    Win32 Version: 1.11.0.0
    CodeBase: file:///C:/Users/erena/Desktop/Deceive.exe
----------------------------------------
System.Memory
    Assembly Version: 4.0.1.1
    Win32 Version: 1.11.0.0
    CodeBase: file:///C:/Users/erena/Desktop/Deceive.exe
----------------------------------------
System.Runtime.CompilerServices.Unsafe
    Assembly Version: 6.0.0.0
    Win32 Version: 1.11.0.0
    CodeBase: file:///C:/Users/erena/Desktop/Deceive.exe
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4341.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4161.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Text.Json
    Assembly Version: 6.0.0.3
    Win32 Version: 1.11.0.0
    CodeBase: file:///C:/Users/erena/Desktop/Deceive.exe
----------------------------------------
System.Buffers
    Assembly Version: 4.0.3.0
    Win32 Version: 1.11.0.0
    CodeBase: file:///C:/Users/erena/Desktop/Deceive.exe
----------------------------------------
System.Numerics.Vectors
    Assembly Version: 4.1.4.0
    Win32 Version: 1.11.0.0
    CodeBase: file:///C:/Users/erena/Desktop/Deceive.exe
----------------------------------------
Microsoft.Bcl.AsyncInterfaces
    Assembly Version: 6.0.0.0
    Win32 Version: 1.11.0.0
    CodeBase: file:///C:/Users/erena/Desktop/Deceive.exe
----------------------------------------
System.Threading.Tasks.Extensions
    Assembly Version: 4.2.0.1
    Win32 Version: 1.11.0.0
    CodeBase: file:///C:/Users/erena/Desktop/Deceive.exe
----------------------------------------
System.Text.Encodings.Web
    Assembly Version: 6.0.0.0
    Win32 Version: 1.11.0.0
    CodeBase: file:///C:/Users/erena/Desktop/Deceive.exe
----------------------------------------
EmbedIO
    Assembly Version: 3.4.3.0
    Win32 Version: 1.11.0.0
    CodeBase: file:///C:/Users/erena/Desktop/Deceive.exe
----------------------------------------
Swan.Lite
    Assembly Version: 3.0.0.0
    Win32 Version: 1.11.0.0
    CodeBase: file:///C:/Users/erena/Desktop/Deceive.exe
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

**Comment by molenzwiebel** [comment]
Please let me know if you still have this issue on [v1.12.1](https://github.com/molenzwiebel/Deceive/releases/tag/v1.12.1).
