### ISSUE TITLE
Friend List not working in Valorant

### ISSUE THREAD

**Issue by BMaKaco** [molenzwiebel/Deceive#172]
I´m having problems with the friend list in valorant, and I can´t invite any of my friends

**Comment by EnderC00kiez** [comment]
yeah you have to be online to use that

**Comment by molenzwiebel** [comment]
For those finding this issue later: this is not intentional. Your friends list should work perfectly fine even with Deceive active. Please report a bug if it is not. Closing this now since it is old and likely fixed by a new version.
