### ISSUE TITLE
Chat not working in League of Legends

### ISSUE THREAD

**Issue by ericseonulee** [molenzwiebel/Deceive#173]
On client, when started with league of legend option, friends chat not working and matchmaking lobby chat says connecting but will not connect. It seems to work fine when started through riot client option.

**Comment by molenzwiebel** [comment]
Please check if you still experience this on [v1.13.0](https://github.com/molenzwiebel/Deceive/releases/tag/v1.13.0), and leave a comment if you do.

**Comment by GiorgosTants** [comment]
> On client, when started with league of legend option, friends chat not working and matchmaking lobby chat says connecting but will not connect. It seems to work fine when started through riot client option.

i had the same issue. to solve this go to %appdata% - local - and remove riot games folder. Restart pc and its solved
