### ISSUE TITLE
wont run after my windows 11 update

### ISSUE THREAD

**Issue by nessageyo** [molenzwiebel/Deceive#176]
![image](https://user-images.githubusercontent.com/126306464/221334366-0bdbd224-2d18-47fa-996c-60af4b74d19b.png)
this error appears and it won't work. my laptop automatically updated from windows 10 to 11 yesterday.

**Comment by soramameee39** [comment]
You can right click to open it. Maybe.

**Comment by RomeoAlphaEkko** [comment]
sometimes get such error windows too, a 2nd try to launch mostly helps

**Comment by molenzwiebel** [comment]
Please send your logs, located in `%appdata%/Deceive/debug.log` if you can still reproduce this.
