### ISSUE TITLE
allow multiple clients not working

### ISSUE THREAD

**Issue by lambilat** [molenzwiebel/Deceive#177]
.

**Comment by aetrnm** [comment]
@lambilat  This app is not supposed to allow you using multiple clients. It was just a video demonstration using Virtual Machine, not an app feature.

**Comment by molenzwiebel** [comment]
As @aetrnm mentioned, multiple clients is not an intended feature and is not documented for public use. The old instructions you've likely found won't work with Deceive's new-ish command line flags anyway.

Try something along the lines of `Deceive.exe --riot-client-params="--allow-multiple-clients" --game-params="--allow-multiple-clients" lol`. No guarantees it'll work though (and it definitely won't allow you to have more than one _game_ instance open at a time).
