### ISSUE TITLE
Deceive

### ISSUE THREAD

**Issue by Garrick667** [molenzwiebel/Deceive#178]
Deceive does not work with the new update I tried to reinstall it but the software disappears from my data when launching the launcher, it would be necessary to update the software so that it is compatible with the update ( league of legends )

**Comment by molenzwiebel** [comment]
If Deceive disappears from your PC, you have an antivirus removing it. In any case, this is not enough information for me to help you.

Try the following:
- Disable your firewall entirely and restart both League and Deceive. If this fixes it, try adding an exception for Deceive and/or League in your firewall.
- If you previously blocked chat using firewall-based methods (such as netsh advfirewall), make sure to remove those blocks before running deceive.
- If you are using antivirus software, make sure it is not blocking Deceive.
- Try running Deceive as administrator (right-click Deceive.exe, "Run as administrator")

If none of these work, please upload your Deceive logs. They can be found in `%AppData%/Deceive/debug.log`.
