### ISSUE TITLE
Update server down when launching League with Deceive

### ISSUE THREAD

**Issue by justlac** [molenzwiebel/Deceive#179]
I get this message when I try to launch League of Legends with deceive :

![image](https://user-images.githubusercontent.com/99365712/229906368-570ce25e-cdf6-472d-8787-2e49d4793ba8.png)

It only happens when I use deceive, launching the games from the riot client will not give me this error.

Clicking on "Retry" will give the same message.

I am using the latest release and I have deleted/re-downloaded Deceive a few times with no change.

Thanks in advance for any help!

**Comment by molenzwiebel** [comment]
Please check if you still experience this on [v1.13.0](https://github.com/molenzwiebel/Deceive/releases/tag/v1.13.0), and leave a comment if you do.
