### ISSUE TITLE
Still getting chat messages and party requests (Valorant)

### ISSUE THREAD

**Issue by LilBenjii** [molenzwiebel/Deceive#180]
I just downloaded Deceive and it installs and runs fine, the bot even appears and I can interact with it, but it doesn't seem to actually work since other people still see me online.

**Comment by molenzwiebel** [comment]
Please confirm for me whether or not you have a "Deceive Active" member in your friends list in [v1.12.1](https://github.com/molenzwiebel/Deceive/releases/tag/v1.12.1). If you don't, you are not actually using Deceive.
