### ISSUE TITLE
Valorant Version Mismatch

### ISSUE THREAD

**Issue by NoelJoubert** [molenzwiebel/Deceive#181]
I am getting the following error when running Valorant using the program:
![image](https://user-images.githubusercontent.com/13378919/231847814-5c0b0774-0c7e-4f65-9a0d-60bbada29fe3.png)

I have tried running it as Admin as well.  Everything else looks fine :)

**Comment by molenzwiebel** [comment]
Solved in [v1.12.1](https://github.com/molenzwiebel/Deceive/releases/tag/v1.12.1).
