### ISSUE TITLE
deceive unable to find path to riot games

### ISSUE THREAD

**Issue by buggysencho22** [molenzwiebel/Deceive#182]
I've already launched valorant countless times and everytime i launch deceive i receive this error. is there any solution that im not aware of or am I doing something wrong

![smth](https://user-images.githubusercontent.com/130775983/232083739-fbfc7dea-176d-44b0-8595-e324b3b24a48.png)

**Comment by molenzwiebel** [comment]
Generally this indicates a corrupt install. If you still have this issue, please paste the contents of `C:/ProgramData/Riot Games/RiotClientInstalls.json` as a comment.
