### ISSUE TITLE
Error message after last patch

### ISSUE THREAD

**Issue by peteratf** [molenzwiebel/Deceive#183]
i have been receiving this error. 
have been using with no problem until last patch i believe. TY
![image](https://github.com/molenzwiebel/Deceive/assets/133285810/ff1c035d-0ce3-478d-9eb5-7e075606e930)
NA server normal install on windows 11. TY

**Comment by molenzwiebel** [comment]
Please check if you still experience this on [v1.13.0](https://github.com/molenzwiebel/Deceive/releases/tag/v1.13.0), and leave a comment if you do.
