### ISSUE TITLE
Deceive has stopped working for me

### ISSUE THREAD

**Issue by AratusNavis** [molenzwiebel/Deceive#185]
Ever since downloading the latest v1.12.1 .exe, Deceive has stopped working. 
![Screenshot (2054)](https://github.com/molenzwiebel/Deceive/assets/135585272/898a0bfa-2714-4403-a4f5-d165fbd00608)
I've no idea about coding or anything, but Deceive has always been working fine up until now where I get this error message whenever I try opening league through it.

**Comment by peteratf** [comment]
i had started receiving this like 2 or 3 patches ago. havent gotten an answer on discord. if you do get it resolved could you msg down here the solution? i will do likewise ty.

**Comment by AratusNavis** [comment]
that long? yikes... will do!

Am Mo., 12. Juni 2023 um 07:37 Uhr schrieb peteratf <
***@***.***>:

**Comment by bit-paper** [comment]
try running deceive as admin, works good for me

**Comment by HelioSnoowy** [comment]
> try running deceive as admin, works good for me @AratusNavis @peteratf

this is worked for me, thankss!
