### ISSUE TITLE
Issue logging in after switching to PBE server (EDIT: Issue Self-Resolved)

### ISSUE THREAD

**Issue by WHotzfeld** [molenzwiebel/Deceive#19]
League v 9.21.294.813
Deceive v 1.5

After logging in multiple times successfully with Deceive on the normal League client (NA server), I switched to playing on the PBE server (without using Deceive). Now, whenever I attempt to launch League via Deceive, the client defaults to the PBE server instead of my local server (NA). 

When I try to switch to the NA server (by changing the server in the upper left part of the client login), the client crashes after I log in (when opened via Deceive).
When I make no switch, I simply log in to PBE instead of NA (I don't want or need to use Deceive on PBE, only NA).
I am still able to launch League and play on the NA server successfully, but only if I do not use Deceive to open League.

I think it may have to do with
var riotClientPath = Utils.GetRiotClientPath();
in the program.cs, but I'm unsure how to remedy the problem.

Any help is appreciated, and glad to provide more info if you need any! 
(ps - Thanks for the app!)   :)

EDIT: ISSUE SELF-RESOLVED.
Within 10 minutes of posting this, Deceive began defaulting to the NA server again. (???) I'll go ahead and leave this issue up, though, in case you can get any use out of the information I provided. The issue itself still exists, as the client crashed after trying to switch servers and logged in via Deceive. But for now, my problem is solved, so feel free to close this issue.

**Comment by aPinat** [comment]
This happens because Deceives remembers the last opened or more importantly the last client that was restarted by Deceive. 
You can reset that yourself by deleting `%AppData%/Deceive/lcuPath` and it should default to standard League again. Otherwise logging into NA and then launching Deceive afterwards and have Deceive restart the client will also set the file to the correct installation.

**Comment by WHotzfeld** [comment]
Ah! Good to know. I'll keep that in mind. Thank you for your work, and thank you for the quick reply! I'll close the issue.
