### ISSUE TITLE
Not working latest patch 19.10.23

### ISSUE THREAD

**Issue by OzzieAus** [molenzwiebel/Deceive#193]
Can't access friend's list or use chat in latest patch

**Comment by Jwong99** [comment]
Same issue with me

**Comment by vDucky** [comment]
same

**Comment by TTSS99** [comment]
SAME

**Comment by darezed** [comment]
anyone got a fix for this?

**Comment by DL108** [comment]
Hi there,

Got the same problem with Deceive 1.12.1 and latest patch
Started VALORANT without Deceive, and working like normal - friends list active & chat also active in-game

So problem is with Deceive & latest patch of VALORANT

Please fix, thanks
D

**Comment by DL108** [comment]
Hi @molenzwiebel 

Any luck on a fix?

**Comment by kylezinsser** [comment]
Same issue here with latest versions of Deceive and Valorant.

I will add that around the time it stopped working, Windows had "randomly" prompted me again for network permissions for Valorant. A friend who doesn't use Deceive got the same Windows prompt. It also seems to take longer to launch through Deceive than it did before.

Networking is not my forte, but I ran things in Visual Studio to see if I could figure anything out. For whatever it's worth, as far as I can tell the Deceive proxy server is talking with the Riot Client just fine. No exceptions or error messages, fake player statuses and messages seemed to be going through, and I could see in the logs that Deceive was successfully getting my Friend's list.

I did find it odd that the XML in `PossiblyRewriteAndResendPresenceAsync` has references to all the different `<games>` elements, and some specific logic when it finds a `<valorant>` element, but when I had it spit out the full xml content into the logs the only game there was `<keystone>`, both when initially launching Valorant and after changing the Deceive status from the system tray. Not sure whether that's normal or if it could be related to why Valorant apparently doesn't know to talk to Deceive anymore.

**Comment by katiksiz-mal** [comment]
Deceive is fixed. Download latest version in discord server.

**Comment by DL108** [comment]
> Deceive is fixed. Download latest version in discord server.

Hi there,
Sorry, new to Discord, but what is the server called?
Tried looking in Valorant, Molenzwiebel but cant "search" for Deceive...

Thanks

**Comment by PratyushPathak** [comment]
> > Deceive is fixed. Download latest version in discord server.
> 
> Hi there, Sorry, new to Discord, but what is the server called? Tried looking in Valorant, Molenzwiebel but cant "search" for Deceive...
> 
> Thanks

Here is the link to the message containing the fixed deceive: https://discord.com/channels/249481856687407104/249481940955037698/1165930434488713250

**Comment by DL108** [comment]
> > > Deceive is fixed. Download latest version in discord server.
> > 
> > 
> > Hi there, Sorry, new to Discord, but what is the server called? Tried looking in Valorant, Molenzwiebel but cant "search" for Deceive...
> > Thanks
> 
> Here is the link to the message containing the fixed deceive: https://discord.com/channels/249481856687407104/249481940955037698/1165930434488713250

Thanks, but all I am getting is no text channels:

![2023-10-24_22-43-54](https://github.com/molenzwiebel/Deceive/assets/76733466/68ae5f57-eedb-4b47-bf3e-e5068b4a3ce7)

**Comment by PratyushPathak** [comment]
> > > > Deceive is fixed. Download latest version in discord server.
> > > 
> > > 
> > > Hi there, Sorry, new to Discord, but what is the server called? Tried looking in Valorant, Molenzwiebel but cant "search" for Deceive...
> > > Thanks
> > 
> > 
> > Here is the link to the message containing the fixed deceive: https://discord.com/channels/249481856687407104/249481940955037698/1165930434488713250
> 
> Thanks, but all I am getting is no text channels:
> 
> ![2023-10-24_22-43-54](https://user-images.githubusercontent.com/76733466/277799760-68ae5f57-eedb-4b47-bf3e-e5068b4a3ce7.jpg)

are you sure you're in the server? here is the invite link for the server: https://discord.gg/bfxdsRC

**Comment by DL108** [comment]
> > > > > Deceive is fixed. Download latest version in discord server.
> > > > 
> > > > 
> > > > Hi there, Sorry, new to Discord, but what is the server called? Tried looking in Valorant, Molenzwiebel but cant "search" for Deceive...
> > > > Thanks
> > > 
> > > 
> > > Here is the link to the message containing the fixed deceive: https://discord.com/channels/249481856687407104/249481940955037698/1165930434488713250
> > 
> > 
> > Thanks, but all I am getting is no text channels:
> > ![2023-10-24_22-43-54](https://user-images.githubusercontent.com/76733466/277799760-68ae5f57-eedb-4b47-bf3e-e5068b4a3ce7.jpg)
> 
> are you sure you're in the server? here is the invite link for the server: https://discord.gg/bfxdsRC

Thank you :)
That is what I was looking for, ahahah

Brilliant,

Also big thanks @molenzwiebel  ;)

**Comment by niccocezar** [comment]
Deceive working in the lobby but team chat becomes disabled while game is on-going.

**Comment by SteffenCarlsen** [comment]
For ease of access to anyone who wants to update:
![image](https://github.com/molenzwiebel/Deceive/assets/9629847/e3813855-b910-45c0-b136-fee3050bee5d)
Direct download from the discord message: https://cdn.discordapp.com/attachments/249481940955037698/1165930434031521813/Deceive.exe?ex=6548a455&is=65362f55&hm=1b85fe3bd853d6fae15282e118525fc9162065b366583af44861d7caa7761957&

Discord link to join the server (Taken from the README): https://discord.gg/bfxdsRC
Direct link the the message in the screenshot: https://discord.com/channels/249481856687407104/249481940955037698/1165930434488713250

**Comment by niccofox** [comment]
> For ease of access to anyone who wants to update: ![image](https://user-images.githubusercontent.com/9629847/278818737-e3813855-b910-45c0-b136-fee3050bee5d.png) Direct download from the discord message: https://cdn.discordapp.com/attachments/249481940955037698/1165930434031521813/Deceive.exe?ex=6548a455&is=65362f55&hm=1b85fe3bd853d6fae15282e118525fc9162065b366583af44861d7caa7761957&
> 
> Discord link to join the server (Taken from the README): https://discord.gg/bfxdsRC Direct link the the message in the screenshot: https://discord.com/channels/249481856687407104/249481940955037698/1165930434488713250

Already updated to this but the chat is only working in the lobby but not during a match.

**Comment by molenzwiebel** [comment]
Fixed in [v1.13.0](https://github.com/molenzwiebel/Deceive/releases/tag/v1.13.0).
