### ISSUE TITLE
Valorant service unavailable ( chat and friend list unavailable )

### ISSUE THREAD

**Issue by F4ll3n1n** [molenzwiebel/Deceive#195]
title... thats it.

**Comment by freza1** [comment]
This was reported 2 weeks ago, I think mole made a slightly different version on the discord but it seems to not work. This might get closed and moved to the older one.

**Comment by molenzwiebel** [comment]
Fixed in [v1.13.0](https://github.com/molenzwiebel/Deceive/releases/tag/v1.13.0).
