### ISSUE TITLE
Deceive not starting up

### ISSUE THREAD

**Issue by L0wk3yL** [molenzwiebel/Deceive#198]
![image_2023-11-17_234224278](https://github.com/molenzwiebel/Deceive/assets/151260947/b39a88fb-1ada-47b9-94da-78ac3af6f4fb)
![image_2023-11-17_234239920](https://github.com/molenzwiebel/Deceive/assets/151260947/06e9dfa5-7ccf-4c26-9d9f-36d56752641d)
I don't have any riot game open and I get these messages. First I could start up valorant on deceive but i couldn't join matches or see my friendlists. So i deleted it and downloaded it again and now I get this!

**Comment by molenzwiebel** [comment]
Run as admin.
