### ISSUE TITLE
Virus or false positive?

### ISSUE THREAD

**Issue by Gitsstates** [molenzwiebel/Deceive#201]
Deceive v1.13.0 on Windows 10.
Should I ignore it?

![310587371](https://github.com/molenzwiebel/Deceive/assets/152910993/ee0302c2-f6e3-4c17-b357-2f8c822b688f)

**Comment by EinfachObli** [comment]
That is just a normal warning, because your pc does not know the program and it isn't signed. It hasn't found a virus or a threat. It just reminds you to be careful with software from unknown sources.

**Comment by molenzwiebel** [comment]
@EinfachObli is correct here. No issues, just Windows telling you to be cautious.
