### ISSUE TITLE
Will the Addition of Vanguard Cause Issues for Deceive?

### ISSUE THREAD

**Issue by AshokaShringla** [molenzwiebel/Deceive#203]
Will Deceive be flagged by Vanguard as a cheat for League of Legends?

**Comment by philipp-heller** [comment]
No, as Valorant used Vanguard for since forever and it works with that.
Also look https://discord.com/channels/249481856687407104/249481856687407104/1194055964169613382 for offical molenzwiebel answering it

**Comment by molenzwiebel** [comment]
@philipp-heller is correct, League transitioning to Vanguard will not have any impact on Deceive.
