### ISSUE TITLE
Deceive uses 100% GPU  

### ISSUE THREAD

**Issue by saidIssaoui** [molenzwiebel/Deceive#208]
I tested the client without deceive and I got stable  usage of GPU 10% - 11% but with deceive it spike to 26% - 29% reaching 100% every  few seconds please fix. 
my pc spec : 
Processor	12th Gen Intel(R) Core(TM) i7-12650H, 2300 Mhz, 10 Core(s), 16 Logical Processor(s)
Installed Physical Memory (RAM)	32.0 GB
NVIDIA GeForce RTX 2050
![image](https://github.com/molenzwiebel/Deceive/assets/47367625/253f1d5d-8d4a-4300-84c1-0b7abd4b6c1b)

**Comment by molenzwiebel** [comment]
Not related to Deceive.
