### ISSUE TITLE
Banned in less than a few hours

### ISSUE THREAD

**Issue by gempir** [molenzwiebel/Deceive#21]
I wouldn't recommend anyone using this tool. I got banned in a few hours. Haven't heard back from riot support yet.

**Comment by molenzwiebel** [comment]
Likely a false positive. In the two years that Deceive has existed, I've had two reports of people getting banned and neither of them ended up being for Deceive. Last report I also double checked with Riot (who is aware of this tool) and they confirmed that at that moment Riot wasn't handing out bans for Deceive. Please leave a comment once/if you hear back from support about your ban and I'll investigate further on my end.

**Comment by gempir** [comment]
Update: The Ban actually was on my 2nd account and I didn't even use that one with deceive. Not sure how I got banned since I haven't logged in a few days but happy to report my Issue was incorrect and *Deceive did not get me banned*
