### ISSUE TITLE
Offercore and Trojan Threat when Downloading

### ISSUE THREAD

**Issue by niccofox** [molenzwiebel/Deceive#221]
I'm getting virus and adware threats after downloading the .exe file of the version-to-date. I confirmed it by downloading multiple times.
![image](https://github.com/molenzwiebel/Deceive/assets/8748843/41988690-bc14-471e-b2ff-158313ccdf6a)

**Comment by Larlenn** [comment]
Can confirm, newest update shows multiple viruses in windows defender, automatically deletes the file

**Comment by oskkas** [comment]
Same
![image](https://github.com/molenzwiebel/Deceive/assets/117778773/0a64c2aa-902f-4dac-9129-1ade200d0e81)

**Comment by brian2k** [comment]
Same here

**Comment by molenzwiebel** [comment]
All false positives, nothing I can do. Your options are:

- Wait for the engines to stop detecting this (and stay on v1.13.1 for now).
- Allow it manually.
- Compile it youself from the source code.

I've submitted the binary but that will take a few days to resolve.
