### ISSUE TITLE
Microsoft Defender - Trojan:Win32/Sabsik.FL.A!ml

### ISSUE THREAD

**Issue by D4ryB3rry** [molenzwiebel/Deceive#225]
Hello,  
  
Whenever i download the new Release-v1.14, Microsoft Defender automatically delets it saying the above mentionod Trojan is in this file.

The is the message i'm getting: 
<img width="387" alt="Deceive_Defender" src="https://github.com/molenzwiebel/Deceive/assets/22527253/c43b9ea0-2002-446b-88fd-aaedd50ae0c7">

And it links to this Microsoft Page:
https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?name=Trojan%3AWin32%2FSabsik.FL.A!ml&threatid=2147780195

I hope you're able to help with this.

**Comment by vogone1** [comment]
I can't download the file because edge tells me its a virus.  
Even if I use the terminal and download with curl it auto deletes the file after a few seconds saying it contains a virus.
I get that windows defender doesn't like 3rd party files from unknown sources but the trojan part is a bit weird.

**Comment by arkdamenen** [comment]
Plus one for me.
If I visit VirusTotal, some of the antiviruses are complaining as well.

![image](https://github.com/molenzwiebel/Deceive/assets/60974195/9a4f85ee-0ca8-4ce6-9660-b43718269594)

https://www.virustotal.com/gui/file/8e51ae8ec954ee023b0d07b3e38d3ee4bd8414c561ab312b892d3a24e4434439

**Comment by lordsim** [comment]
same

**Comment by molenzwiebel** [comment]
#221
