### ISSUE TITLE
Nod32 Found Virouses

### ISSUE THREAD

**Issue by DrDevitor** [molenzwiebel/Deceive#233]
Hello
Thanks for your hard-work and efforts.
as you can see in the photo, nod32 found the file is corrupted and deleted it immediately afterwards.

So please take a look into it and fix it for further use.

Many thanks

Best Regards
Ali

![image](https://github.com/user-attachments/assets/7721667f-fd53-4753-91e9-68e249db672c)

**Comment by molenzwiebel** [comment]
False positive. Whitelist it in your antivirus.

**Comment by DrDevitor** [comment]
ive done everything, it still getting removed and deleted by liveguard eset and cant do anything to stop it ...

**Comment by DrDevitor** [comment]
I have downloaded V1.13 and works fine. no need to change anything in nod32

**Comment by DrDevitor** [comment]
something is wrong in your V1.14 somehow ... I dont know what but try to take a look over it 
thanks btw.
