### ISSUE TITLE
Hello, I'm from China. How to use this program?

### ISSUE THREAD

**Issue by yushifu1233** [molenzwiebel/Deceive#247]
I tested this program in the Internet bar and on my own computer. It may be because of regional problems that it cannot be used. What can be done to solve this problem? If possible, please help me. Thank you.

**Comment by molenzwiebel** [comment]
Not compatible with chinese servers.

**Comment by yushifu1233** [comment]
> 与中国服务器不兼容。

Thank you. Your program brings more fun to the game experience, and I will continue to pay attention to your works. I wish you happy every day.
