### ISSUE TITLE
PBE server launches instead of normal client

### ISSUE THREAD

**Issue by Varirus** [molenzwiebel/Deceive#26]
I was using deceive with PBE installed and it worked correctly, but after league of legends client update and new feature stay singed in, it seems to work incorrectly. I try to turn deceive on, but it launches PBE client and i can't change it anywhere.

**Comment by molenzwiebel** [comment]
Looks like Deceive has defaulted to launching PBE. You can fix it by launching your normal League manually, then launching Deceive and allowing it to restart your League.

**Comment by Varirus** [comment]
Oh ok, Thank you
