### ISSUE TITLE
Still appearing online - OCE

### ISSUE THREAD

**Issue by Brodster1000** [molenzwiebel/Deceive#28]
Not sure if I am doing anything wrong, but I am loading league up through deceive 1.5.1 and its still showing me as online. It doesn't appear in the taskbar either so I can't change anything through there.

**Comment by aPinat** [comment]
Yeah, you have the new chat system that is being tested on PBE and OCE. Current versions of Deceive do not work on both servers. Check back later, when a fix is released!

**Comment by Brodster1000** [comment]
Ah I see, thank you.
