### ISSUE TITLE
Patch 9.24 - Deceive not working?

### ISSUE THREAD

**Issue by GoldenKaiser** [molenzwiebel/Deceive#30]
Restarted Deceive a couple times including running as admin and it looks like it's not hiding my status.

[Also this](https://imgur.com/a/ldzaG90)

**Comment by aPinat** [comment]
You are running an outdated version, can you try it with the latest one? Also, which region are you on?

**Comment by GoldenKaiser** [comment]
Strange. I was pretty sure I was running 1.6. which is the current version. Anyhow, it seems to be working now when I re-downloaded the program again. 

To answer your question, I am playing in the NA region.
