### ISSUE TITLE
Patch 9.24 - Spectating match changes my status ONLINE

### ISSUE THREAD

**Issue by GoldenKaiser** [molenzwiebel/Deceive#33]
Sorry if I am creating another issue report but today I was spectating a friend's game and surprisingly after his match ended, he noticed me online. I then try to replicate the issue by spectating another player on my friend list. I then opened League+ on my phone and was surprised my main account went from offline to online.

I am currently running the latest version of Deceive and I play in the NA region.

**Comment by aPinat** [comment]
I can't seam to replicate that myself, but it sounds like Deceive never actually works then.. Deceive is supposed to ALWAYS mask your status, through everything you do in the client or what the client itself displays to you...

Would you mind checking whether this happens on v1.5.1 as well? https://github.com/molenzwiebel/Deceive/releases/tag/v1.5.1

**Comment by GoldenKaiser** [comment]
> I can't seam to replicate that myself, but it sounds like Deceive never actually works then.. Deceive is supposed to ALWAYS mask your status, through everything you do in the client or what the client itself displays to you...
> 
> Would you mind checking whether this happens on v1.5.1 as well? https://github.com/molenzwiebel/Deceive/releases/tag/v1.5.1

Sadly I downloaded v1.5.1 and it does not work for me. I see it on the tray icon for a moment and then it disappears. More importantly, I was still shown ONLINE.

**Comment by aPinat** [comment]
Ok, so Deceive doesn't work at all for you.. Hmm... Did you use Deceive before or maybe moved your League install somewhere else? Where is League located, if not in the standard folder (C:/Riot Games/League of Legends)? Do you have PBE installed and tried to use Deceive on PBE before?

Also try deleting the folder %AppData%/Deceive and try again...

**Comment by GoldenKaiser** [comment]
Deceive is on my regular HDD and LoL is on my SSD. I will put Deceive on my SSD if it matters. Deceive does work for me it's just that when I spectate my friends, my status is showing "Spectating" and as soon as I stop watching the match I go right back to offline.

**Comment by aPinat** [comment]
No, it shouldn't matter where Deceive is, as long as it finds the correct League install.
But you said, that it shows as Online for friends and on the League+ app...
Whatever is shown in your client locally (especially the blue statuses, like "In Game", "Spectating", "In Queue") should only be visible to you, but the status should still be fully masked to others as offline. That is, when Deceive works properly.

**Comment by GoldenKaiser** [comment]
I mean I never had problems like this before this new patch and I spectating my peers while offline. Could the new patch 9.24 may have created this issue?

**Comment by aPinat** [comment]
Hmm, the new patch hasn't changed anything in terms of chat, at least for NA... PBE and OCE are testing the new chat system, but afaik NA isn't affected yet. 
So you mean, this patch it shows "Spectating" to others and the League+ app, but before not (even though it's always shown in our own client)?
Do you have PBE installed?

**Comment by GoldenKaiser** [comment]
Yeah here is the situation: So I log into my main account thru Deceive on PC. I then have my phone logged into a smurf account. Smurf and main account are friends. When I spectate a match on PC, my phone shows my main account go from offline to "Spectating". 

To answer your question, I do have PBE.

**Comment by aPinat** [comment]
Ok, so did you try deleting Deceives %AppData% folder?
Alternatively you can also log into League without Deceive and then run Deceive so it get's the right configuration and restarts the League client.

**Comment by GoldenKaiser** [comment]
Sure. I'll try that tomorrow since it's getting pretty late here.

**Comment by molenzwiebel** [comment]
Just to be sure, **do not delete your entire AppData folder**! Just delete the Deceive folder inside of it (`%appdata%/Deceive`).

**Comment by GoldenKaiser** [comment]
So I deleted the Deceive folder in AppData and looks like I am still getting the same result when I go spectate a match.

**Comment by aPinat** [comment]
Hmm.. Can you verify that, the lcuPath-file in %AppData%/Deceive is indeed where your current League install is located and not pointing to somewhere else? (You can just open that file in any text editor like Notepad)
I also just checked, NA is also using the new chat system now, so you'll have to use Deceive 1.6.0 or later.

**Comment by aPinat** [comment]
I've had a deeper look into this and Deceive is supposed to be working just fine on NA as well..
Did your Riot Client maybe have to patch or restart after starting with Deceive?
As I'm really running out of ideas of what may causes this, could you add me on NA (aPinat) and ping me here when you have time to do a quick test, so I can check myself?

**Comment by aPinat** [comment]
Should be fixed in #35 or https://github.com/aPinat/Deceive/releases/tag/20191216.1.

**Comment by GoldenKaiser** [comment]
Alright, just got home from work and downloaded the version with the link provided above. Looks like it's working! Hooray! 👌

**Comment by KeppKep** [comment]
May I know how to prevent this error , thank you!
![Untitledhd](https://user-images.githubusercontent.com/58966852/70966679-fc82be00-20ce-11ea-8838-bcfd0a084f9b.jpg)

**Comment by aPinat** [comment]
@KeppKep Looks like you're running Windows 8/8.1, maybe your .NET Framework is outdated.
Can you try installing the latest version and try again?
https://dotnet.microsoft.com/download/dotnet-framework

**Comment by KeppKep** [comment]
> @KeppKep Looks like you're running Windows 8/8.1, maybe your .NET Framework is outdated.
> Can you try installing the latest version and try again?
> https://dotnet.microsoft.com/download/dotnet-framework
can i run it under .NET 4.5?

**Comment by aPinat** [comment]
Well, Deceive is targeting 4.6.1, but there is no harm in installing the latest version, especially since 4.5 has reached end of life a couple years ago and isn't supported anymore.

**Comment by KeppKep** [comment]
> Well, Deceive is targeting 4.6.1, but there is no harm in installing the latest version, especially since 4.5 has reached end of life a couple years ago and isn't supported anymore.

Thank you, i can run it after installing 4.6.1
