### ISSUE TITLE
Friend list not showing

### ISSUE THREAD

**Issue by Voidblade-1** [molenzwiebel/Deceive#36]

**Comment by Voidblade-1** [comment]
Friend list is not showing EUW:
https://i.imgur.com/iOuzFgt.png

**Comment by Voidblade-1** [comment]
Restarted my PC and apparently it's showing now.

**Comment by aPinat** [comment]
Sometimes Deceive couldn't connect to chat servers, so the friends list doesn't appear and chat doesn't work at all. Typically just retrying and launching League with Deceive again should fix it.

**Comment by Voidblade-1** [comment]
Yea I just restarted my PC and it's working fine now. First time happening to me which is weird. But all good now.
