### ISSUE TITLE
Status Not Staying

### ISSUE THREAD

**Issue by Oblituarius** [molenzwiebel/Deceive#37]
Version in use: 1.6.1
After launching League with Deceive everything looks fine.
As soon as I start to create a lobby or go in game, my League status switches back. Already verified it login into my smurf on my laptop and checking my main status. I have to manually change it for it to stick during a game.

**Comment by aPinat** [comment]
Can you try this version and see if that fixes it? https://github.com/aPinat/Deceive/releases/latest

**Comment by GoodCreativeUsername123** [comment]
Until this is fixed block ports 5222 5223 but that will disable all social parts of the client

**Comment by eco999** [comment]
> 
> 
> Can you try this version and see if that fixes it? https://github.com/aPinat/Deceive/releases/latest
> 
> 10.1 generally is very buggy in terms of chat. Friends list not appearing, Open Parties not joinable, Hovercards not working correctly even for online users and list goes on...

This didn't fix it for me.

**Comment by aPinat** [comment]
@eco999 What exactly should it have fixed? Do you have the exact same issue as the issue opener? If yes, have you also verified, that it's really showing you as online/In Game to others, since it's normal that it shows that to you locally.

**Comment by eco999** [comment]
@aPinat Yes, I have the same issue as OP. 
I left it on and my friend told me it said I was online.

**Comment by aPinat** [comment]
Which region are you on and do you have Riot Client installed and are using it to login (instead of i.e. circumventing it..)?

**Comment by eco999** [comment]
Region: EUW
I am using the Riot client to login but I have auto-login enabled if that matters.

**Comment by aPinat** [comment]
Ok, no that shouldn't matter, I'll have a closer look into it tomorrow... Would you mind posting LeagueClient Log and Riot Client Log after starting with the Deceive version above?

**Comment by eco999** [comment]
After further inspection, I believe my issue is unrelated. Mb

**Comment by Oblituarius** [comment]
I can post my logs tomorrow, my region is LAN and I also have auto logging just as eco999.

**Comment by aPinat** [comment]
@Oblituarius Have you tried this version and verified that your status is shown to others and not just showing for you locally? https://github.com/aPinat/Deceive/releases/latest

**Comment by Oblituarius** [comment]
AH I didn't know there was a release yesterday. I just checked the same way as on my first post
Run Decieve on main PC.
Run smurf on laptop.
Go ingame on main.
Status is updated while still ingame / queue / lobby.
New version working! Thanks @aPinat

**Comment by aPinat** [comment]
Oh I didn't realize you were the one who opened the issue.. :-D
Great, it's working! ;-)

**Comment by molenzwiebel** [comment]
This should be merged into master as of v1.7.0.
