### ISSUE TITLE
Deceive is broken in the current league patch

### ISSUE THREAD

**Issue by triipex** [molenzwiebel/Deceive#4]
Currently, the deceive program does not function in the current league of legends patch (8.8). This means that when launching league from deceive.exe , whilst it does say that your presence is showing as offline, you are still in fact visible to everyone on your friends list.
I have no idea about the coding for this program or how to fix it, just letting the creators know about this issue.
Cheers,
Triipex

**Comment by molenzwiebel** [comment]
Thanks, I'll investigate!

**Comment by molenzwiebel** [comment]
I wasn't able to reproduce the issue:

![](https://i.imgur.com/FhRtnYY.jpg)

As you can see, I still show as offline even though I am online. 

Does it happen consistently? You can always join the [discord](https://discord.gg/bfxdsRC) and ping me if you need help.

**Comment by triipex** [comment]
So ive been testing things, and it seems as though whenever i log on using the program, i am showing online as shown in the picture attached. However, if i then disable and re-enable deceive, i then show as offline. 
![evidence](https://user-images.githubusercontent.com/38514232/39415097-9a8be3d8-4c82-11e8-93c7-b9fbb9eca152.JPG)
