### ISSUE TITLE
Deceive encountered an error and couldn't properly initialize itself

### ISSUE THREAD

**Issue by paulletta3** [molenzwiebel/Deceive#40]
Tried to launch deceive on my new laptop and this error popped up 
Note: My OS is in portuguese so the translation might not be 100% accurate 
System.TypeInitializationException: The Type initialization of 'Deceive.Utils' added an exception. --->
System.IO.FileNotFoundException: Could not be able to load file or assembly 'system.Net.Http, version=4.2.0.0, Culture=neutral
PublicKeyToken=b03f5f7f11d50a3a' or one of dependencies. The system could not find the specified file. 

My League client is installed on C:\Riot Games
The same error happens for the 1.6.1 version of deceive. Please help D:

**Comment by aPinat** [comment]
Oh, you really typed all that out :-O 
It essentially means your .NET install (probably because Windows isn't updated) is outdated, install latest from here: https://dotnet.microsoft.com/download/dotnet-framework/net48

**Comment by paulletta3** [comment]
Ooh now it makes sense. Thank you so much, i totally forgot about .NET update
