### ISSUE TITLE
Champ select and post game chat

### ISSUE THREAD

**Issue by funghetto** [molenzwiebel/Deceive#44]
Sometimes the champ select chat works other times not, the post game chat always doesn't work.
 Is it to be expected?

**Comment by aPinat** [comment]
Yep, that's a known bug, it's fixed in #43.
The automated pre-release builds over on my repo have that fix and should be working:
https://github.com/aPinat/Deceive/releases/latest

**Comment by funghetto** [comment]
Thanks that version seems to work, I'll leave this open until it gets an official release.

**Comment by aPinat** [comment]
Fix for this was released in v1.8.0.
https://github.com/molenzwiebel/Deceive/releases/tag/v1.8.0
