### ISSUE TITLE
deceive occasionally doesnt work

### ISSUE THREAD

**Issue by Booyja** [molenzwiebel/Deceive#46]
So when i logg in, it says i am offline, after returning from a game i am suddenly online.
This started to happen 3 or 2 days ago.

Edit: I have tested the v1.6.1 release, wich works just fine.

**Comment by aPinat** [comment]
You mean the status overlay isn't showing up after a game, or takes a bit to show?
Or do you mean, you are really showing as online to friends and not just locally on your own client?
Since what is shown on your own client isn't always accurate.

**Comment by Booyja** [comment]
The Status overlay isnt showing up and i am shown as Online with the green light. I dont know if its just showing online but i am actually offline.

**Comment by aPinat** [comment]
Yeah, typically it will still be masking you for others in the background. The overlay is just for you to remind you that the status is being masked, so what your own client shows can be incorrect at times.

**Comment by Booyja** [comment]
Allright, i will doublechecked and its the overlay that is dissapearing at times. Thanks for the support.
