### ISSUE TITLE
Not working when Riot folder it's not in the default place

### ISSUE THREAD

**Issue by kanazaca** [molenzwiebel/Deceive#48]
Hello,

I have my Riot Game folder in my secondary drive, when i run Deceive, it tasks for the folder, then i set the folder and the program don't run anymore.
I can start how many times i want, it wont start up.

Regards.

**Comment by aPinat** [comment]
You must be running a quite outdated version, since newer versions get the install path automatically and does not the user where it is.
Use either: https://github.com/molenzwiebel/Deceive/releases/latest
or: https://github.com/aPinat/Deceive/releases/latest

**Comment by kanazaca** [comment]
You are completely right sorry!
