### ISSUE TITLE
There was an unexpected error with the login session. Please try again.

### ISSUE THREAD

**Issue by zotoro** [molenzwiebel/Deceive#49]
Today I've started receiving a new error I've never encountered before whenever I try to log into League using Deceive. I get a message through league saying that there was an unexpected error with the login session, and to exit and try again.

After exiting League I'm then given the following error code:

> Deceive encountered an error and couldn't properly initialize itself. Please contact the creator through....
> System.InvalidOperationException: Sequence contains no elements
> at System.Linq.Enumerable.First[TSource](IEnumerable'1 source)
> at Deceive.MainController..ctor(Boolean isLeague)
> at Deceive.StartupHandler.StartDeceive(String[] cmdArgs)
> at Deceive.StartupHandler.Main(String[] args)

Any ideas on what is causing this and how I can fix it? At the moment I cannot use Deceive as it causes League to crash every time I log in

**Comment by aPinat** [comment]
I believe this happens, when Deceive is faster to initialize the connection to chat servers than the LeagueClient showing up or the LeagueClient being closed again already.
This might have something to do with the current global login and server issues League is facing.
Please try to reproduce this at a later time again...

**Comment by molenzwiebel** [comment]
I left a comment about this on your most recent PR @aPinat. Might be worth fixing this while we're at it.

**Comment by aPinat** [comment]
Fixed in #50 / https://github.com/molenzwiebel/Deceive/releases/tag/v1.8.0 .
