### ISSUE TITLE
Deceive v1.8.0 Status Reset and Crashing

### ISSUE THREAD

**Issue by Oblituarius** [molenzwiebel/Deceive#51]
I just updated Deceive to test it out. It worked for the first few seconds, after that, the client switched back to online status, chat got disconnected and Deceive closed itself.
Leaving it here a this is a new update, in case the dev needs some error samples.

Edit1: Don't know if it is intended, but when clicking out of the League client, the status overlay switches over to online green text (want to know if it is just visual or not).
I believe Deceive is crashing if you start changing the overlay option.

Edit2: I don't touch the tray icon, it seems to stay working fine. The status change from Edit1 still keeps happening.

**Comment by aPinat** [comment]
> I just updated Deceive to test it out. It worked for the first few seconds, after that, the client switched back to online status, chat got disconnected and Deceive closed itself.
> Leaving it here a this is a new update, in case the dev needs some error samples.

Ok, that sounds like the overlay just straight up crashed... 

> Edit1: Don't know if it is intended, but when clicking out of the League client, the status overlay switches over to online green text (want to know if it is just visual or not).
> I believe Deceive is crashing if you start changing the overlay option.

Yeah, the overlay is for you as a reminder, it serves no actual masking purpose, and it is supposed to disappear when you click/tab out so it doesn't overlay over something else.

> Edit2: I don't touch the tray icon, it seems to stay working fine. The status change from Edit1 still keeps happening.

Can you post the contents of `debug.log` in `%AppData%/Deceive` right after the crash happens?

**Comment by Oblituarius** [comment]
<Can you post the contents of debug.log in %AppData%/Deceive right after the crash happens?
> 
I actually checked %AppData%/Deceive just after the first time it crashed. It is still 0 bytes, completely empty.
It just crashed as soon as the client switched to ingame and it is still 0 bytes, do you still want it?

**Comment by aPinat** [comment]
Oh, yeah it looks like we weren't handling the exceptions coming from the overlay...
If you can still reproduce the issue, this version should properly log exceptions from the overlay: https://github.com/aPinat/Deceive/releases/tag/20200419.2

> Edit2: debug.log now has something after closing the game, not sure if usefull.

Ah, that is just the perfectly normal exception that get's thrown when you close the Client and the connection to chat was closed.. Actually should be there and is a sign that Deceive worked correctly, as long as you closed the client yourself and it didn't crash on its own. 😉

**Comment by Oblituarius** [comment]
> If you can still reproduce the issue, this version should properly log exceptions from the overlay: https://github.com/aPinat/Deceive/releases/tag/20200419.2
Probably still can, I will download this and attempt to do it.

**Comment by Oblituarius** [comment]
Doesn't seem to be crashing anymore, at least not with the release you gave me for debugging. I guess we can close the issue and just reopen in case it reappears.
