### ISSUE TITLE
Deceive ends task and disconnects from chat after overlay toggle

### ISSUE THREAD

**Issue by WHotzfeld** [molenzwiebel/Deceive#53]
To preface, this issue has only occurred once so far.

Opened the client via Deceive as I normally do. Options selected: 
Enabled: [yes]
Status type: [offline]
Show overlay status: [yes] (although this was not displaying properly)
Enable lobby chat: [yes]

After opening, noticed overlay status was not displaying properly. Toggled this option off and on again; overlay began displaying. Immediately queued for ARAM. After game, did not connect to post-game lobby chat. In addition, friends list sidebar displayed "You have been disconnected from chat" with the "uh oh" Poro icon.
Still in post-game lobby, checked running tasks, Deceive was not in use (not just disabled, task was not running at all). Had to restart client to reconnect to chat and activate Deceive.

UPDATE: After restart, Overlay Status was not displaying again. Toggled off and on, and the overlay began functioning. However, after stepping away from computer for 1 or 2 minutes (client was in menus, not in queue), was disconnected from friends list chat again, and deceive was not running, same as before. Appears to be directly connected to "overlay status" function.

**Comment by aPinat** [comment]
Can you run this version: https://github.com/aPinat/Deceive/releases
and post the exception log in `%AppData%/Deceive`?
If the current version also has those logs, you can use the current one too.
Also, yeah, the overlay is still kind of buggy and doesn't immediately display sometimes, but it should appear after clicking outside and in LCU...

**Comment by WHotzfeld** [comment]
Sorry for late reply. Still buggy like you said but seems to work as intended apart from the overlay. Thanks for the response. Closing this issue.
