### ISSUE TITLE
Start Up Error

### ISSUE THREAD

**Issue by bunnnbunn** [molenzwiebel/Deceive#55]
I've uninstalled and reinstalled both deceive and league and i don't know enough to fix this start up error

![2ba4cf0e3bee9e6cb3f840afd47d0837](https://user-images.githubusercontent.com/64818927/81028285-b0060800-8e4e-11ea-9b3e-5120ff6359bc.png)

**Comment by Token07** [comment]
You need to update your .net framework runtime.
https://dotnet.microsoft.com/download/dotnet-framework/net48
