### ISSUE TITLE
Unable to launch Valorant

### ISSUE THREAD

**Issue by Wrothfuss** [molenzwiebel/Deceive#57]
![image](https://user-images.githubusercontent.com/64928085/81225135-bca57000-8fb6-11ea-8853-62781204099c.png)

After trying to follow the gif provided I this error continued to happen.  What am I doing wrong?

**Comment by molenzwiebel** [comment]
Sorry for the confusion! You'll need to move your double quote (`"`) so that it sits after the .exe instead of after valorant. In other words, it'll need to look like `Deceive.exe" valorant` instead of `Deceive.exe valorant"`. Then it should all work.
