### ISSUE TITLE
Unable to see friend list

### ISSUE THREAD

**Issue by xerus6** [molenzwiebel/Deceive#59]
After you sign out and log back again, the friend list doesn't show http://postimg.cc/mhSv6J3s , and you also don't get access to the menu from the application in the taskbar.

**Comment by DocCobra** [comment]
Hey! Have you tried using the latest release in the aPinat fork? https://github.com/aPinat/Deceive/releases

**Comment by aPinat** [comment]
You cannot sign out and log back in when you use Deceive, you need to fully close League and the Riot Client and then start with Deceive again, since Deceive is unable to reconnect to the chat server or fetch the new configuration for the new user without reinitialization.
