### ISSUE TITLE
Deceive works for one account but not another

### ISSUE THREAD

**Issue by kcwoodwa** [molenzwiebel/Deceive#60]
I have two Valorant accounts and was able to get deceive working on the first but it wouldn't work for the second. The loading screen hangs for a while on the second and then the game will load with my friends list disconnected and empty. I tried deleting %AppData% folders thinking it might be some sort of configuration that was messing things up but still had the same issue.

**Comment by aPinat** [comment]
Can you try https://github.com/aPinat/Deceive/releases and see if that works?

**Comment by kcwoodwa** [comment]
Yup, it did! Thanks for the quick reply.
