### ISSUE TITLE
Friends list missing only on new accounts

### ISSUE THREAD

**Issue by RynLee** [molenzwiebel/Deceive#61]
I recently went ahead and made a new account but whenever I login to the new account my friends list and missions are all missing (https://imgur.com/a/w4aaN6l). When I log back into my main account the friends list is there.

**Comment by aPinat** [comment]
This is due to Riot now assigning a chat server they deem best to your account, instead of the one associated with your League region.
Has been updated here: https://github.com/aPinat/Deceive/releases/latest

**Comment by molenzwiebel** [comment]
Please let me know if this is still an issue with v1.10.0.
