### ISSUE TITLE
Can’t get Deceive to work 

### ISSUE THREAD

**Issue by Galaxyor** [molenzwiebel/Deceive#62]
I am trying to make it work on Windows 10 for Valorant. I downloaded the exe, put it in my download folder, made a shortcut that is now on my desktop, and in properties added ` valorant ` in the end of the Target path. However, when I double click to start it, it just does nothing. I tried running as administrator and still nothing happens. Am I doing something wrong ?
Here is how my properties look like :
![image](https://user-images.githubusercontent.com/7620969/83758775-dcda5480-a672-11ea-846a-5c2e20b3b378.png)

**Comment by aPinat** [comment]
Hmm, that looks correct actually.. Do have League installed or play League? If yes, does Deceive work normally with League, or does it also not start at all when opening directly without the shortcut?

**Comment by Galaxyor** [comment]
I do not have league and I don't play league, but i can try to download the game and try.

**Comment by Galaxyor** [comment]
Just installed LOL and tried to run the exe (without shortcut), and there's still nothing happening. Also tried redownloading Deceive but it doesnt fix it.

**Comment by aPinat** [comment]
What's the content of `C:\ProgramData\Riot Games\RiotClientInstalls.json`? Is there no error message at all? If so is your antivirus maybe blocking the startup of the program?

**Comment by Galaxyor** [comment]
Here are the contents of the json file:
![image](https://user-images.githubusercontent.com/7620969/83765459-7ad21d00-a67b-11ea-9872-520b83e1cdb4.png)
There are no error messages when I run deceive. 
My antivirus doesn't seem to be blocking anything.

**Comment by aPinat** [comment]
Looks fine actually, can you try this: https://cdn.discordapp.com/attachments/249660919494344704/718104804022550678/Deceive.exe
And post any error messages that show up in `%AppData%/Deceive`?

**Comment by Galaxyor** [comment]
Ok I just tried to troubleshoot the program using the windows troubleshooter. It worked for league, so I pressed save curent settings and then tried with valorant. and this time I got an error:
![image](https://user-images.githubusercontent.com/7620969/83768540-35afea00-a67f-11ea-998b-6e19cc944f21.png)
I am going to now try with the file you just sent me.

**Comment by aPinat** [comment]
Oh that error just popped up, because the other Deceive instance was still running.. Be sure to close all Deceive instances in Task Manager when testing the version I sent, otherwise it can't log anything to the file...

**Comment by Galaxyor** [comment]
Thank you for your help!

**Comment by Galaxyor** [comment]
One more question is there a way to invite friends in Valorant while apearing offline?

**Comment by aPinat** [comment]
https://github.com/molenzwiebel/Deceive/issues/58#issuecomment-626763096

**Comment by Galaxyor** [comment]
oh alright just read it, thank you. But disabling or enabling doesn't seem to work. Is there anything I can do about that?

**Comment by aPinat** [comment]
What do you mean exactly? Keep in mind, that you can't see the effect in your own game client.

**Comment by Galaxyor** [comment]
Well I uncheck the enable box and then when I go in game after a few seconds if i check the deceive icon again the enable box is checked.

**Comment by Galaxyor** [comment]
Also I can't reopen the deceive menu after i change the enable setting. I have to wait for it to reenable by itself I wonder if maybe I'm doing anything wrong.

**Comment by aPinat** [comment]
That is very strange behavior.. Might be because of your compatibility settings. Deceive is not made for Windows XP, and was only tested on Windows 10, but should also work on Windows 7 and up.
