### ISSUE TITLE
Deceive Stopped Working on Valorant After Patch Today

### ISSUE THREAD

**Issue by ir1417** [molenzwiebel/Deceive#63]
![image](https://user-images.githubusercontent.com/64977677/83819441-b4f0ee00-a67e-11ea-9bb2-0efa37813d5f.png)

My Valorant client updated today and now I receive this message when trying to launch via Deceive. If I use the client by itself, it works fine.

**Comment by aPinat** [comment]
I can't reproduce that. Since it says "compatibility mode settings", do you have any enabled for Deceive? If yes, disable them.

**Comment by ir1417** [comment]
Weird, I removed Run as Administrator and now it works. Thanks for your help!

**Comment by molenzwiebel** [comment]
Please let me know if this is still an issue with v1.10.0.

**Comment by molenzwiebel** [comment]
Wait I can't read
