### ISSUE TITLE
Valorant friends list disconnected after playing 1 or 2 matches

### ISSUE THREAD

**Issue by puffbro** [molenzwiebel/Deceive#64]
It works fine until the friends list inevitably disconnect after a few matches (service unavailble). When the friend list disconnect the tray icon menu become unresponsive (clicking enable does not change the tick). I'm playing on SEA server in win10. It also seems like entering the practice range always disconnect the friend list.

Update: It seems like switch to borderless windows fix this issue. I was using fullscreen.
Update: The friend list still disconnect after a while with borderless.

**Comment by aPinat** [comment]
Try: https://github.com/aPinat/Deceive/releases

**Comment by puffbro** [comment]
How do you enable deceive for valorant on your release?
