### ISSUE TITLE
Dont know how to use decieve 

### ISSUE THREAD

**Issue by Baobao249** [molenzwiebel/Deceive#65]
Hey im not sure how i get it to work to begin with

**Comment by aPinat** [comment]
Well, you download and run it?

**Comment by Baobao249** [comment]
there is no application to run 
only codes i think.

**Comment by aPinat** [comment]
You need to go to the releases tab for the downloads.

**Comment by Baobao249** [comment]
o its my first time using these thanks for the help!

**Comment by Baobao249** [comment]
where do i go to find that..

**Comment by aPinat** [comment]
https://github.com/molenzwiebel/Deceive/releases
OR
https://github.com/aPinat/Deceive/releases
