### ISSUE TITLE
League of Legends occasionally disables the friend list

### ISSUE THREAD

**Issue by Frontear** [molenzwiebel/Deceive#68]
When running the game with Decieve, it will occasionally not load the friend list, leaving it a black rectangle. I'm certain this issue is being caused by Decieve, as it does not happen when I run the client through its normal launch method.

**Comment by aPinat** [comment]
Try https://github.com/aPinat/Deceive/releases

**Comment by weiwang11** [comment]
Still occurs with your latest release.

**Comment by SHRoberts91** [comment]
Same for me, @aPinat, as well with your release deceive will crash a few seconds after the league client loads up. This is occurring on Ver. 20200629.1

**Comment by molenzwiebel** [comment]
Please let me know if this is still an issue with v1.10.0.
