### ISSUE TITLE
Newest patch broke it?

### ISSUE THREAD

**Issue by marcelherd** [molenzwiebel/Deceive#7]
I've been using a firewall rule to appear offline, but today I noticed that its not working anymore. I tried Deceive as well with no luck. I am playing on EUW. Does anyone else have the same issue?

**Comment by molenzwiebel** [comment]
Riot rolled out some large infrastructure changes with 9.14 that impacted how chat works. Deceive should only be broken on OCE and RU right now though. What issues are you experiencing? Is Deceive failing to launch or is chat fundamentally broken (showing an empty friends list/attempting to reconnect)?

**Comment by marcelherd** [comment]
@molenzwiebel It launches just fine but I do not appear as offline at all

**Comment by molenzwiebel** [comment]
You confirmed with a different account that you're shown as online? When using Deceive, client-side still shows you as online even though your presence is hidden.

**Comment by marcelherd** [comment]
@molenzwiebel Apparently it doesnt mask online status for mobile users - I checked it on my phone using the Android app and another account.

I asked a friend to check for me and I do show up as offline using the desktop client - that works for me. Thanks!

**Comment by scmanjarrez** [comment]
I tried to start it but I'm getting this error.
![image](https://user-images.githubusercontent.com/9284124/61563077-1c0bb100-aa73-11e9-8293-0f900e29152a.png)

**Comment by Token07** [comment]
You need to delete the RADS folder.

**Comment by scmanjarrez** [comment]
@Token07 That worked perfectly, thanks!!
