### ISSUE TITLE
Version Mismatch (v1.10.0)

### ISSUE THREAD

**Issue by McNinjaTNT** [molenzwiebel/Deceive#73]
I'm getting this error. (See attached image)
![Capture](https://user-images.githubusercontent.com/69410086/89724425-b52ba380-d9b7-11ea-912e-70ed44bd89b5.PNG)

**Comment by Teksteeeks** [comment]
same issue :"0

**Comment by McNinjaTNT** [comment]
> same issue :"0
Still works I guess, asked a friend and ti showed I was offline so ye.

**Comment by Shnxxx** [comment]
Is this still working? Even it is version mismatched? Valorant updated so much right now.

**Comment by Ayinaki** [comment]
It still works, even if the version mismatch is there. Just a visual bug since valorant updated.

**Comment by molenzwiebel** [comment]
Like @Ayinaki said, Deceive is still active.
