### ISSUE TITLE
[Suggestion] Chat Control

### ISSUE THREAD

**Issue by TheMadHau5** [molenzwiebel/Deceive#79]
With Valorant on full-screen, switching Deceive modes (via Win+D or Alt-Tab) is difficult and may cause bugs in Valorant, as it is designed to stay in focus at all times. To solve this, I'm suggesting adding chat control to the Deceive fake player (maybe something like "online" to make Deceive show you as online, and "offline" for offline).
Thanks!

**Comment by aPinat** [comment]
I implemented that a while ago over on my repo, commands are: `offline, mobile, online, enable, disable, status`
https://github.com/aPinat/Deceive/releases
Should be included in the next release here too, when there are enough changes to justify that.

Screenshot from League, but works same in VALORANT
![image](https://user-images.githubusercontent.com/17106472/97804898-f0560f80-1c52-11eb-9885-6924b59cf964.png)

**Comment by TheMadHau5** [comment]
Thank you, that's very convenient. I'll compile your repository, then.

**Comment by molenzwiebel** [comment]
This is now included in v1.11.0.
