### ISSUE TITLE
It couldn't properly Initalize

### ISSUE THREAD

**Issue by EarthyRain** [molenzwiebel/Deceive#82]
Whenever I start up Deceive V1.10.0 it shows up with this.
![decieve acting fucky](https://user-images.githubusercontent.com/74274189/98745088-7f140c00-2378-11eb-9f77-a046dd1a3dc8.PNG)

I use Deceive for only Valorant and I do not have LoL installed.

**Comment by aPinat** [comment]
A Riot Client file got 'corrupted' probably due to an update or installing a new game, usually launching the game/Riot Client without Deceive should fix it.

**Comment by EarthyRain** [comment]
Thank you for the quick answer, that did fix it. Thank you.
