### ISSUE TITLE
Client closes after launch and deceive application get deleted.

### ISSUE THREAD

**Issue by Sonicerx** [molenzwiebel/Deceive#83]
Hi,

Whenever I launch deceive for Valorant, the client opens but after 5 seconds it closes and the deceive application is deleted from the directory I installed it on, and I have to reinstall it again.

This happened today as of 14/11. I have been using it for a month without problems.

Any solutions?

**Comment by molenzwiebel** [comment]
This is likely some anti-virus messing with Deceive. Since Deceive is the one to launch VALORANT, once it is killed/deleted VALORANT closes with it. Try adding an exemption for Deceive in your antivirus.

**Comment by Sonicerx** [comment]
Spot on. I did not think about it at all since I did not change anything in my antivirus.

It's working now. Thank you 👍
