### ISSUE TITLE
League can't find internet connection

### ISSUE THREAD

**Issue by sm4sh** [molenzwiebel/Deceive#84]
The latest update broke Deceive.

After starting you're being greeted by the "League can't find internet connection" splash screen and that's it.  
Using the usual launcher works.

**Comment by aPinat** [comment]
Typically happens when the Riot Client had to update and restart itself.
Deceive isn't being restarted with it, so if you just launch Deceive again after it finished patching (or launching without Deceive once helps too), it should all work as usual again.

**Comment by sm4sh** [comment]
Oops! Sorry for bothering, then.
