### ISSUE TITLE
Dando erro quando logo na conta

### ISSUE THREAD

**Issue by Miyne844** [molenzwiebel/Deceive#90]
Ta dando mensagem de erro quando vou usar o deceive, da erro e o chat fica todo apagado
![decevie](https://user-images.githubusercontent.com/79610654/109078659-79022b00-76dc-11eb-89b9-14a037e23f01.png)

**Comment by molenzwiebel** [comment]
This looks like a problem with your internet or the Riot servers, not something caused by Deceive.
