### ISSUE TITLE
[Information Request] Utilizing the proxy to send reminders to self

### ISSUE THREAD

**Issue by CaelFrost** [molenzwiebel/Deceive#98]
If i wanted to create a script that sends messages to the localhosted proxy, would that be do-able?

**Comment by aPinat** [comment]
If you want to send messages to Riot's chat servers you should rather use RC or LCU API instead of trying to connect to the local proxy Deceive creates, because that does not really work.
Regardless, it is also possible to connect to chat servers directly without RC since they use normal XMPP.

**Comment by CaelFrost** [comment]
The purpose was to do something like a script that is meant to send myself a reminder on a regular interval, not communicate outside of my own client.

**Comment by aPinat** [comment]
Oh, then it would probably be easiest to edit the 'fake Deceive player' to send you any message you want and put a timer behind it.
But isn't it a bit unnecessary to send reminders for yourself inside the client, and not just use some alarm/timer or reminder program?
